### ISSUE TITLE
Authorization funktioniert nicht

### ISSUE THREAD

**Issue by paulstegmann** [europace/report-api#5]
Hallo zusammen,

wir wollen die API testen und scheitern am Login - wir erhalten wir drei verschiedene User den gleichen Fehler:

{{access_token}}
not a valid key=value pair (missing equal-sign) in Authorization header
{{access_token}}

![image](https://user-images.githubusercontent.com/14310061/101024002-d1a9a800-3573-11eb-8c5e-8b10d6f0431f.png)

Alle User haben die Berechtigung für report:rohdaten:lesen.

Grüße
Paul

**Comment by dnltsk** [comment]
Danke für die Info. 

Verstehe ich es richtig, dass die Fehlermeldung vom `https://api.europace.de/auth/token`-Endpunkt kommt? Vielleicht kannst Du uns noch ein paar mehr Details zuschicken? Welche Query Parameter und Header wurden wohin geschickt? 

Ein funktionierender Login wäre bspw.
```
curl --location --request POST 'https://api.europace.de/auth/token?grant_type=client_credentials' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Authorization: Basic {creds}'
```

Wobei `{creds}` == `{user}:{pass}` als base64 encoded

Beste Grüße,
Daniel

**Comment by paulstegmann** [comment]
Hallo Daniel,

der Login klappt soweit und der Token daraus auch bei den anderen APIs, nur nicht bei dieser API. Der User hat auch die Recht für diese API:

![image](https://user-images.githubusercontent.com/14310061/102090968-6e92fd80-3e1e-11eb-8357-1bc4a7593acf.png)

Kannst du uns ggf. eine Collection für die Report-API einstellen? Evtl. liegt es an einem Parameter.

Danke und Grüße
Paul

**Comment by dnltsk** [comment]
Der [/documentation](https://report.api.europace.de/documentation)-Endpunkt liefert ein OpenAPI 3.0-Dokument, dass bspw in Postman importiert werden kann.

Ansonsten sollte dies hier ein funktionierender Request sein, der die Erzeugung eines neuen Rohdaten-Reports auslöst:

```
curl --location --request POST 'https://report.api.europace.de/rohdaten' \
--header 'Authorization: Bearer {access_token}' \
--header 'Content-Type: application/json' \
--data-raw '{
    "fromDay": "2020-01-01"
}'
```

Ggf. könnt Ihr einen `X-Trace-Id`-Header mitschicken, sodass wir euren konkreten Request auf unserer Seite genauer prüfen können.

**Comment by dnltsk** [comment]
@paulstegmann Konntet Ihr das Problem lösen?

**Comment by MikeKrueger75** [comment]
@paulstegmann die aktuelle Postman-Collection enthält auch die Report-API.

**Comment by paulstegmann** [comment]
> @paulstegmann Konntet Ihr das Problem lösen?

@dnltsk Hi! Ja - mittlerweile läuft es, danke.
